### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by zalubom** [egoist/is-trademarked-cli#2]
Hi All,

just throwing this error into:

hedgy-osx:opt$ is-trademarked kik
/usr/local/lib/node_modules/is-trademarked-cli/cli.js:3
const meow = require('meow')
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by vkeusebio** [comment]
What's the version of your Node.js?

**Comment by egoist** [comment]
Sure it requires node>= 4

**Comment by egoist** [comment]
There should a warning when you install this module like:

```bash
npm WARN engine is-trademarked-cli@1.4.2: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})
npm WARN engine is-trademarked@1.2.1: wanted: {"node":">=4"} (current: {"node":"0.12.7","npm":"2.11.3"})
```

**Comment by zalubom** [comment]
thats what i wanted to say with my post, sorry i was in a hurry ;-)
thanks for this tool, i use it regularly ....
